spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: biblioteca
          uri: lb://BIBLIOTECA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/biblioteca/**
        - id: endereco
          uri: lb://ENDERECO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/endereco/**
        - id: livro
          uri: lb://LIVRO-SERVICE
          filters:
          - StripPrefix=1
          predicates:
          - Path=/livro/**
eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
server:
  port: 9098
