app:
  myport: ${PORT:0}
spring:
  application:
    name: biblioteca-service
  datasource:
    url: jdbc:h2:mem:biblioteca
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2: 
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
server:
  port: ${app.myport}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      enderecoService: 
        sliding-window-size: 3
        minimum-number-of-calls: 1
        wait-duration-in-open-state: 10000
        register-health-indicator: true
      livroService: 
        register-health-indicator: true
        wait-duration-in-open-state: 10000
        minimum-number-of-calls: 1
        sliding-window-size: 3
